"use client";
export type CastEntry={name:string;character_name:string|null;photo:string|null;display_order:number};
export type CompanyEntry={name:string;logo:string|null};
export type AwardEntry={award_id?:number;name:string;category:string|null;year:number|null;result:'Won'|'Nominated'|null;recipient:string|null};
export type Structured={cast:CastEntry[];companies:CompanyEntry[];awards:AwardEntry[]};
export default function MetadataEditor({value,change}:{value:Structured;change:(value:Structured)=>void}){
 function cast(i:number,patch:Partial<CastEntry>){change({...value,cast:value.cast.map((r,n)=>i===n?{...r,...patch}:r)});}
 function company(i:number,patch:Partial<CompanyEntry>){change({...value,companies:value.companies.map((r,n)=>i===n?{...r,...patch}:r)});}
 function award(i:number,patch:Partial<AwardEntry>){change({...value,awards:value.awards.map((r,n)=>i===n?{...r,...patch}:r)});}
 return <div className="structured-metadata"><h3>Cast (optional)</h3>{value.cast.map((r,i)=><div className="metadata-row" key={i}><label>Person’s name<input required maxLength={255} value={r.name} onChange={e=>cast(i,{name:e.target.value})}/></label><label>Character / role<input maxLength={255} value={r.character_name||''} onChange={e=>cast(i,{character_name:e.target.value})}/></label><label>Photo URL<input maxLength={2000} value={r.photo||''} onChange={e=>cast(i,{photo:e.target.value})}/></label><label>Display order<input type="number" min={0} max={10000} required value={r.display_order} onChange={e=>cast(i,{display_order:Number(e.target.value)})}/></label><button type="button" className="text-button" onClick={()=>change({...value,cast:value.cast.filter((_,n)=>n!==i)})}>Remove cast entry</button></div>)}<button type="button" className="secondary-button" onClick={()=>change({...value,cast:[...value.cast,{name:'',character_name:'',photo:'',display_order:value.cast.length}]})}>+ Add cast</button>
 <h3>Production houses (optional)</h3>{value.companies.map((r,i)=><div className="metadata-row" key={i}><label>Company name<input required maxLength={255} value={r.name} onChange={e=>company(i,{name:e.target.value})}/></label><label>Logo URL<input maxLength={2000} value={r.logo||''} onChange={e=>company(i,{logo:e.target.value})}/></label><button type="button" className="text-button" onClick={()=>change({...value,companies:value.companies.filter((_,n)=>n!==i)})}>Remove production house</button></div>)}<button type="button" className="secondary-button" onClick={()=>change({...value,companies:[...value.companies,{name:'',logo:''}]})}>+ Add production house</button>
 <h3>Awards (optional)</h3>{value.awards.map((r,i)=><div className="metadata-row" key={i}><label>Award / event name<input required maxLength={255} value={r.name} onChange={e=>award(i,{name:e.target.value})}/></label><label>Category<input maxLength={255} value={r.category||''} onChange={e=>award(i,{category:e.target.value})}/></label><label>Year<input type="number" min={1800} max={2200} value={r.year??''} onChange={e=>award(i,{year:e.target.value?Number(e.target.value):null})}/></label><label>Result<select required={!r.award_id} value={r.result||''} onChange={e=>award(i,{result:e.target.value as AwardEntry['result']})}>{!r.result&&<option value="">Legacy record — unspecified</option>}<option>Won</option><option>Nominated</option></select></label><label>Recipient<input maxLength={255} value={r.recipient||''} onChange={e=>award(i,{recipient:e.target.value})}/></label><button type="button" className="text-button" onClick={()=>change({...value,awards:value.awards.filter((_,n)=>n!==i)})}>Remove award</button></div>)}<button type="button" className="secondary-button" onClick={()=>change({...value,awards:[...value.awards,{name:'',category:'',year:null,result:'Won',recipient:''}]})}>+ Add award</button></div>;
}
