"use client";
import { useEffect, useState } from 'react';
import { api, type User } from './api';
import Dialog from './dialog';
type Report={report_id:number;post_id:number|null;title:string|null;content:string|null;author:string|null;author_id:number|null;reason:string;explanation:string;status:string;hidden:boolean;deleted_at:string|null;created_at:string;history:{action_id:number;actor:string;action:string;reason:string;created_at:string}[]};
type Notification={notification_id:number;report_id:number;read_at:string|null};
export default function Moderation({user}:{user:User}){
 const [rows,setRows]=useState<Report[]>([]),[status,setStatus]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[version,setVersion]=useState(0),[focus,setFocus]=useState<number|null>(null);
 const [notifications,setNotifications]=useState<Notification[]>([]),[unread,setUnread]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [selected,setSelected]=useState<Report|null>(null),[action,setAction]=useState('review'),[reason,setReason]=useState(''),[expiry,setExpiry]=useState(''),[confirmation,setConfirmation]=useState('');
 useEffect(()=>{const c=new AbortController();Promise.resolve().then(()=>{if(c.signal.aborted)return;setLoading(true);setError('');return Promise.all([api<{items:Report[];hasMore:boolean}>(`/api/account/moderation/reports?status=${encodeURIComponent(status)}&offset=${offset}${focus?`&report_id=${focus}`:''}`,{signal:c.signal}),api<{items:Notification[];unread:number}>('/api/account/moderation/notifications',{signal:c.signal})]);}).then(result=>{if(result&&!c.signal.aborted){const [r,n]=result;setRows(r.items);setMore(r.hasMore);setNotifications(n.items);setUnread(n.unread);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[status,offset,version,focus]);
 function choose(r:Report,a:string){setSelected(r);setAction(a);setReason('');setExpiry('');setConfirmation('');setError('');}
 return <section className="moderation-panel"><h2>Community reports</h2><p>Review reported stories, record a reason, and keep the community welcoming.</p>
 {user.role==='admin'&&<details><summary>Notifications {unread>0?`● ${unread} unread`:'— all read'}</summary>{notifications.map(n=><button className="text-button" key={n.notification_id} onClick={async()=>{try{await api(`/api/account/moderation/notifications/${n.notification_id}`,{method:'PATCH'});setStatus('');setOffset(0);setFocus(n.report_id);setVersion(v=>v+1);}catch(e){setError((e as Error).message);}}}>{n.read_at?'':'● '}Report #{n.report_id}</button>)}</details>}
 <div className="detail-actions"><label>Status <select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);setFocus(null);}}>{['','Open','Under Review','Escalated','Resolved','Dismissed'].map(s=><option key={s} value={s}>{s||'All statuses'}</option>)}</select></label><button className="secondary-button" onClick={()=>{setFocus(null);setVersion(v=>v+1);}}>Refresh queue</button></div>
 {error&&!selected&&<p className="message error" role="alert">{error}</p>}{loading?<p role="status">Loading reports…</p>:!rows.length?<p>No reports in this queue.</p>:rows.map(r=><article className="community-post" key={r.report_id}><small>#{r.report_id} · {r.status} · {new Date(r.created_at).toLocaleString()}</small><h3>{r.title||'Removed story'}</h3><p>By {r.author||'Deleted account'}{r.hidden?' · Hidden':''}{r.deleted_at?' · Removed':''}</p>{r.content&&<p style={{whiteSpace:'pre-wrap'}}>{r.content}</p>}<p><strong>{r.reason}</strong> {r.explanation}</p><div className="detail-actions">{['review','dismiss','escalate','resolve',...(!r.deleted_at&&r.post_id?[r.hidden?'unhide':'hide']:[]),...(user.role==='admin'&&r.post_id?[...(!r.deleted_at?['delete']:[]),'suspend','unsuspend']:[])].map(a=><button className="secondary-button" key={a} onClick={()=>choose(r,a)}>{({review:'Under review',dismiss:'Dismiss',escalate:'Escalate to Admin',resolve:'Resolve',hide:'Hide story',unhide:'Unhide story',delete:'Delete story',suspend:'Suspend author',unsuspend:'Unsuspend author'} as Record<string,string>)[a]}</button>)}</div><details><summary>Moderation history ({r.history.length})</summary>{r.history.map(h=><p key={h.action_id}><strong>{h.actor||'Deleted account'}</strong> · {h.action} · {new Date(h.created_at).toLocaleString()}<br/>{h.reason}</p>)}</details></article>)}
 <div className="detail-actions"><button className="secondary-button" disabled={loading||!offset} onClick={()=>setOffset(n=>Math.max(0,n-20))}>Previous</button><button className="secondary-button" disabled={loading||!more} onClick={()=>setOffset(n=>n+20)}>Next</button></div>
 {selected&&<Dialog busy={busy} title="Moderation action" close={()=>{setSelected(null);setError('');}}><form className="account-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(`/api/account/moderation/reports/${selected.report_id}`,{method:'PATCH',body:JSON.stringify({action,reason,confirmation,expires_at:expiry?new Date(expiry).toISOString():null})});setSelected(null);setVersion(v=>v+1);window.dispatchEvent(new Event('chitraverse:reports-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2>{action[0].toUpperCase()+action.slice(1)} — report #{selected.report_id}</h2><label>Reason<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{action==='suspend'&&<label>Expiry (optional)<input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>}{action==='delete'&&<><p>The story will be removed from public view and retained for Admin audit.</p><label>Type “{selected.title}” to confirm<input required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>}{error&&<p className="message error" role="alert">{error}</p>}<button className="primary-button" disabled={busy||!reason.trim()}>{busy?'Saving…':'Confirm action'}</button></form></Dialog>}
 </section>;
}
