"use client";
import { useEffect, useState } from 'react';
import { api, type User } from './api';
import Dialog from './dialog';
import type { CommunityPost } from './community-story';
type Comment={comment_id:number;user_id:number;name:string;content:string;created_at:string};
export default function StoryActions({post,user,signIn,changed}:{post:CommunityPost;user:User|null;signIn:()=>void;changed:()=>void}){
 const [open,setOpen]=useState(false),[comments,setComments]=useState<Comment[]>([]),[count,setCount]=useState(post.comment_count||0),[more,setMore]=useState(false);
 const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[content,setContent]=useState('');
 const [editing,setEditing]=useState<Comment|null>(null),[mode,setMode]=useState<'report'|'edit'|'delete'|null>(null),[title,setTitle]=useState(post.title),[story,setStory]=useState(post.content);
 const [reason,setReason]=useState('Spam'),[explanation,setExplanation]=useState('');
 const [action,setAction]=useState<{comment:Comment;kind:'hide'|'delete'}|null>(null),[why,setWhy]=useState('');
 async function load(append=false){setLoading(true);setError('');try{const d=await api<{comments:Comment[];total:number;hasMore:boolean}>(`/api/media/community/${post.post_id}/comments?after=${append?comments.at(-1)?.comment_id||0:0}`);setComments(c=>append?[...c,...d.comments]:d.comments);setCount(d.total);setMore(d.hasMore);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[open]); // eslint-disable-line react-hooks/exhaustive-deps
 async function mutate(path:string,method:string,body?:object){setBusy(true);setError('');setNotice('');try{await api('/api/account/community/'+path,{method,...(body?{body:JSON.stringify(body)}:{})});return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <div className="story-actions">
 <div className="detail-actions"><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}>{count} {count===1?'comment':'comments'}</button>
 {user?.user_id===post.user_id?<><button className="text-button" onClick={()=>setMode('edit')}>Edit story</button><button className="text-button" onClick={()=>setMode('delete')}>Delete story</button></>:<button className="text-button" onClick={()=>user?setMode('report'):signIn()}>Report story</button>}</div>
 {error&&<p className="message error" role="alert">{error}<button onClick={()=>void load()}>Retry comments</button></p>}{notice&&<p role="status">{notice}</p>}
 {open&&<section aria-label="Story comments" className="story-comments">{comments.map(c=><article key={c.comment_id}><strong>{c.name}</strong><small> · {new Date(c.created_at).toLocaleString()}</small><p style={{whiteSpace:'pre-wrap'}}>{c.content}</p><div className="detail-actions">
 {user?.user_id===c.user_id&&<button className="text-button" onClick={()=>{setEditing(c);setContent(c.content);}}>Edit</button>}
 {(user?.user_id===c.user_id||user?.role==='admin')&&<button className="text-button" onClick={()=>{setWhy('');setAction({comment:c,kind:'delete'});}}>Delete</button>}
 {user&&['moderator','admin'].includes(user.role||'')&&user.user_id!==c.user_id&&<button className="text-button" onClick={()=>{setWhy('');setAction({comment:c,kind:'hide'});}}>Hide</button>}</div></article>)}
 {loading&&<p role="status">Loading comments…</p>}{more&&<button className="secondary-button" disabled={loading} onClick={()=>void load(true)}>Load more comments</button>}
 {user?<form className="account-form" onSubmit={async e=>{e.preventDefault();if(await mutate(editing?`comments/${editing.comment_id}`:`${post.post_id}/comments`,editing?'PATCH':'POST',{content})){setContent('');setEditing(null);await load();}}}><label>{editing?'Edit comment':'Join the conversation'}<textarea required maxLength={2000} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="primary-button" disabled={busy||!content.trim()}>{busy?'Saving…':editing?'Save comment':'Post comment'}</button>{editing&&<button type="button" className="text-button" onClick={()=>{setEditing(null);setContent('');}}>Cancel edit</button>}</form>:<button className="secondary-button" onClick={signIn}>Sign in to comment</button>}</section>}
 {mode&&<Dialog busy={busy} title={mode==='report'?'Report story':mode==='edit'?'Edit story':'Delete story'} close={()=>{setMode(null);setError('');}}><form className="account-form" onSubmit={async e=>{e.preventDefault();const ok=await mutate(mode==='report'?`${post.post_id}/reports`:String(post.post_id),mode==='report'?'POST':mode==='edit'?'PATCH':'DELETE',mode==='report'?{reason,explanation}:mode==='edit'?{title,content:story}:undefined);if(ok){setMode(null);if(mode==='report')setNotice('Report submitted. The moderation team will review it.');else changed();}}}>
 <h2>{mode==='report'?'Report story':mode==='edit'?'Edit story':'Delete this story?'}</h2>{mode==='report'?<><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}>{['Spam','Harassment','Hate or abusive content','Inappropriate content','Misinformation','Other'].map(r=><option key={r}>{r}</option>)}</select></label><label>Explanation (optional)<textarea maxLength={2000} value={explanation} onChange={e=>setExplanation(e.target.value)}/></label><p>Your identity is private from the author and ordinary members.</p></>:mode==='edit'?<><label>Title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Story<textarea required maxLength={10000} value={story} onChange={e=>setStory(e.target.value)}/></label></>:<p>Your story and its comments will no longer be publicly available.</p>}
 {error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'Saving…':mode==='delete'?'Confirm delete':mode==='report'?'Submit report':'Save story'}</button></form></Dialog>}
 {action&&<Dialog busy={busy} title={`${action.kind} comment`} close={()=>setAction(null)}><form className="account-form" onSubmit={async e=>{e.preventDefault();if(await mutate(`comments/${action.comment.comment_id}`,action.kind==='delete'?'DELETE':'PATCH',{action:action.kind,reason:why})){setAction(null);await load();}}}><h2>{action.kind==='hide'?'Hide':'Delete'} comment?</h2>{user?.user_id!==action.comment.user_id&&<label>Reason<textarea required maxLength={2000} value={why} onChange={e=>setWhy(e.target.value)}/></label>}{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy}>Confirm</button></form></Dialog>}
 </div>;
}
